[workspace]
authors = ["kutt27 <satheesanamal6@gmail.com>"]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "decision-agent"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
mojo = ">=1.0.0b2.dev2026060606,<2"
python = "<=3.10"
requests = ">=2.34.2,<3"
